### PR TITLE
Revamped DropletCreateActivity UX/UI

### LINKED ISSUE #111: Revamp the UX/UI of the DropletCreateActivity
Revamp the UX/UI of the DropletCreateActivity
**Original**
Screenshot_20190523-202233
**Revamped**
Screenshot_20190526-185056

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #111 
Revamped DropletCreateActivity UX/UI.

### CODE REVIEW

**Comment by jddeep** [comment]
@championswimmer @aggarwalpulkit596 Done 👍 Please merge. Thanks.

**Comment by aggarwalpulkit596** [comment]
Do they look good to you? Please use some decent design, card corner aren't even visible and text inside the cards look extremely bad

**Comment by jddeep** [comment]
> 
> 
> Do they look good to you? Please use some decent design, card corner aren't even visible and text inside the cards look extremely bad

@aggarwalpulkit596 Can you be more specific with the design
Like I added the rounded corners, improved text format, etc..
What more can be improved?
Do you want a larger rounded radius?

**Comment by jddeep** [comment]
@aggarwalpulkit596 Have a look now at the image

**Comment by aggarwalpulkit596** [comment]
Text size is extremely big improper padding/margin etc i shouldn't be telling you these basic building blocks of UX check other apps/websites for reference obviously for adding a card making rounded corners i can't give you any points for this and revamping layouts means some improvisation which is actually appreciable don't do stuff just to get points try to actually do something meaningful otherwise there's no point participating in this or any other competition

**Comment by jddeep** [comment]
@aggarwalpulkit596 Thanks. Just was checking with my expectations. Will do the text formatting. The content in a single card is so much that you can't really revamp a whole lot. Still i have made a lot of formats. I felt the text size is cool as it will get the attention of the user also keeping in mind accessibility. Hope you understand. But anyways will reduce size and all now.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Have a look now please at the image.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Any updates/feedback?

**Comment by jddeep** [comment]
@aggarwalpulkit596 I have made your requested changes. Can you please update me or tell me if something more or else needs to be changed. Thanks.

**Comment by aggarwalpulkit596** [comment]
Travis is failing

**Comment by jddeep** [comment]
> Travis is failing

@aggarwalpulkit596 It is trying to launch an emulator. And there is some problem regarding that.

**Comment by aggarwalpulkit596** [comment]
Read the error and try to fix that

**Comment by jddeep** [comment]
@aggarwalpulkit596 It is showing ` Emulator is out of date ` . But my SDK tools are updated locally.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Even in the previous PR we merged, we had this `Emulator outdate` problem.

**Comment by aggarwalpulkit596** [comment]
So create a seperate issue and fix this first

**Comment by jddeep** [comment]
@aggarwalpulkit596 Please merge this as builds have been resolved. Also please increase the bounties on this.

**Comment by jddeep** [comment]
@aggarwalpulkit596  Please merge this as builds have been resolved. Also please increase the bounties on this.

**Comment by jddeep** [comment]
@aggarwalpulkit596 @championswimmer Can we please get this merged? Changes requested were made. Also please update the bounty on the issue for this as aforesaid. Thank you.

**Pull request merged**
