### PR TITLE
Travis fix for emulator build failures

### LINKED ISSUE #115: Fix Travis builds
Remove Emulator checks in Travis builds.

This causes build failures currently.

### PR DESCRIPTION
**Pull request by jddeep**
Fixes #115 
Travis fix for emulator build failures.

### CODE REVIEW

**Comment by jddeep** [comment]
WIP

**Comment by jddeep** [comment]
@aggarwalpulkit596 It is trying to launch adb from a wrong place. I am making the PR from Windows but it seems it is looking up from Linux point of view. Any suggestions?

**Comment by jddeep** [comment]
@championswimmer @aggarwalpulkit596 Currently the error is : `Unable to detect adb version, adb output: /usr/local/android-sdk/platform-tools/adb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /usr/local/android-sdk/platform-tools/adb)` . I have tried many changes in the .yml file, changes locally but this particular error log seems not to get fixed. Any ideas?

**Comment by jddeep** [comment]
> 
> 
> @championswimmer @aggarwalpulkit596 Currently the error is : `Unable to detect adb version, adb output: /usr/local/android-sdk/platform-tools/adb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /usr/local/android-sdk/platform-tools/adb)` . I have tried many changes in the .yml file, changes locally but this particular error log seems not to get fixed. Any ideas?

@aggarwalpulkit596 I HAVE FIXED THE EMULATOR ERROR but I have been working for days trying to resolve this error. The builds run fine and have been successful here locally.

**Comment by jddeep** [comment]
> 
> 
> > @championswimmer @aggarwalpulkit596 Currently the error is : `Unable to detect adb version, adb output: /usr/local/android-sdk/platform-tools/adb: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.16' not found (required by /usr/local/android-sdk/platform-tools/adb)` . I have tried many changes in the .yml file, changes locally but this particular error log seems not to get fixed. Any ideas?
> 
> @aggarwalpulkit596 I HAVE FIXED THE EMULATOR ERROR but I have been working for days trying to resolve this error. The builds run fine and have been successful here locally.

**Comment by jddeep** [comment]
@aggarwalpulkit596 The `jacocoTestReport` gives errors like `No view with id xyz was found in the view hierarchy` but I looked through the layouts and it's bindings, everything was fine and even the layouts got created in the app perfectly. Why do you think this is happening?

**Comment by aggarwalpulkit596** [comment]
You have changed the layouts so you have to the change it in instrumentation test as well

**Comment by jddeep** [comment]
@aggarwalpulkit596 First of all the layout which I changed, was in a different branch. Here in this branch everything is same. Moreover, the test failures are of different layouts.

**Comment by jddeep** [comment]
@aggarwalpulkit596 I have checked the layouts thoroughly, they are completely fine with correct ids. We can do one thing. I have fixed the emulator test fails and `./gradlew build` fails. You can merge this and see the latter error yourself once.

**Comment by jddeep** [comment]
@championswimmer @aggarwalpulkit596 There were also some errors of `validatesigning`. I took care of those as well, as you can see from the files changed. Thanks.

**Comment by aggarwalpulkit596** [comment]
The exception which Travis is showing is that 
`com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /usr/local/android-sdk/platform-tools/adb`
you need to fix that first

**Comment by jddeep** [comment]
> The exception which Travis is showing is that
> `com.android.builder.testing.api.DeviceException: Could not create ADB Bridge. ADB location: /usr/local/android-sdk/platform-tools/adb`
> you need to fix that first

There is no such issue for `adb` when I run the `jacocoTestReport` locally. I think the project's travis needs to be changed completely, need to remove lot of things. Cause otherwise this `adb` issue persists over here, have tried every possible solution I could find.

**Comment by aggarwalpulkit596** [comment]
JacocoTestReport is an different thing and not at all connected to Travis read about Travis on their website

**Comment by jddeep** [comment]
> JacocoTestReport is an different thing and not at all connected to Travis read about Travis on their website

But in the Travis build log here, the command for which the test is failing is jacocoTestReport.

**Comment by jddeep** [comment]
So naturally i need to test that command locally. But that command does not gives any adb error locally. Instead gives some missing layout ids stuff which i haven't changed anything.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Did you get what i am saying?

**Comment by aggarwalpulkit596** [comment]
The point is that there is nothing wrong JacocoTestReport but the tools and emulator which Travis build for generating report are obsolete and needs to be updated

**Comment by jddeep** [comment]
> The point is that there is nothing wrong JacocoTestReport but the tools and emulator which Travis build for generating report are obsolete and needs to be updated

I am trying different ways and will keep on trying. One thing, so do I need to simply update the $BUILD_TOOLS?

**Comment by jddeep** [comment]
@aggarwalpulkit596 @championswimmer Have fixed the error mentioned for Issue #116 . Now it is upto you guys (admins) to care of this : 
`Execution failed for task ':app:validateSigningRelease'. Keystore file not set for signing config release`

**Comment by jddeep** [comment]
@aggarwalpulkit596 Please merge this ASAP so that I can proceed with further issues.

**Comment by jddeep** [comment]
@aggarwalpulkit596 I have claimed the bounty for this and some others. Please accept them. Thanks.

**Pull request merged**
