### PR TITLE
Code Coverage >50 %

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
screen shot 2018-05-19 at 5 32 44 pm
https://github.com/coding-blocks/DigitalOceanApp/issues/59

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya codecliate is showing error for variable declartion and import statements again again do i need to fix it ?

**Comment by championswimmer** [comment]
Ignore codeclimate stuff for now

**Comment by aggarwalpulkit596** [comment]
@championswimmer okay bhaiya
Kindly check the pull request regarding the code coverage issue

**Comment by championswimmer** [comment]
Some errors on Travis still

```
in.tosc.digitaloceanapp.activities.DropletActivityTest > testDropletInfo[test(AVD) - 5.0.2] FAILED 
	android.support.test.espresso.PerformException: Error performing 'single click' on view 'with text: is "Settings"'.
	at android.support.test.espresso.PerformException$Builder.build(PerformException.java:82)
:app:connectedDebugAndroidTest FAILED
```

**Comment by aggarwalpulkit596** [comment]
Will fix that in a moment

**Comment by aggarwalpulkit596** [comment]
there was some lines of codes which have been removed by a recent commit creating that Travis error which i have fixed with rebasing

**Pull request merged**
