### PR TITLE
Fix travis and circle ci error

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
#106

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya it be merged it was pushed before 12

**Comment by championswimmer** [comment]
you can fix the circle ci part in this PR itself, as you had done major work before deadline. minor fixes can be added to PRs. new claims cannot be made

**Comment by aggarwalpulkit596** [comment]
@championswimmer i have made the claim already i will getting the 2000 points right ?

**Comment by aggarwalpulkit596** [comment]
@championswimmer both have been fixed :)

**Comment by aggarwalpulkit596** [comment]
@championswimmer bhaiya circle 2.0 doesn't support emulators so we can't have instrumentation test right now
https://support.circleci.com/hc/en-us/articles/360000028928-Testing-with-Android-emulator-on-CircleCI-2-0

**Comment by championswimmer** [comment]
oh, lets do only unit tests on circleci then

**Comment by championswimmer** [comment]
> @championswimmer i have made the claim already i will getting the 2000 points right ? 

yes

**Comment by aggarwalpulkit596** [comment]
i have updated circle to 2.0 will i be getting some extra points for that 📦  other than that 2000 points

**Comment by aggarwalpulkit596** [comment]
@championswimmer i think we can't do unit test as well :P
i tried running the tests locally and here what i got
screenshot 2018-08-16 at 1 08 03 am

**Comment by championswimmer** [comment]
that's what you are supposed to fix 😮

**Comment by aggarwalpulkit596** [comment]
@championswimmer it can't be done because they are instrumented test and they need a real device for that  😜 and there is only one unit test 
https://github.com/coding-blocks/DigitalOceanApp/blob/master/doandroidlib/src/test/java/in/tosc/doandroidlib/DigitalOceanTest.java

**Comment by championswimmer** [comment]
yea just run this https://github.com/coding-blocks/DigitalOceanApp/blob/master/doandroidlib/src/test/java/in/tosc/doandroidlib/DigitalOceanTest.java on circleci

I thought you got an error on this test.

**Comment by championswimmer** [comment]
as in just run `test` not `connectedCheck` on circleci

**Comment by aggarwalpulkit596** [comment]
Okay this can be done :+1:

**Pull request merged**
