### PR TITLE
Updated the app usage gif

### LINKED ISSUE #107: update the app usage gif

### PR DESCRIPTION
**Pull request by jddeep**
Updated the app usage gif.

Fixes #107

### CODE REVIEW

**Comment by jddeep** [comment]
@championswimmer @aggarwalpulkit596 Please review and merge. Thanks.

**Comment by aggarwalpulkit596** [comment]
Build is Faling

**Comment by jddeep** [comment]
> 
> 
> Build is Faling

Yes because it is initailizing some emulator which I don't have. I run apps on an actual device.

**Comment by jddeep** [comment]
@aggarwalpulkit596 Other than that there are no problems whatsoever

**Comment by aggarwalpulkit596** [comment]
Check Log Crash of Travis And Read About Travis what does it do

**Comment by jddeep** [comment]
@aggarwalpulkit596 I have checked the Travis log. It is showing `waiting for emulator` which is causing the crash.

**Pull request merged**
