### PR TITLE
Update of dependencies and build tools

### PR DESCRIPTION
**Pull request by 4lch4**
# PR Request to update dependencies and build tools

## What's it do?

Updates the Gradle build tools, Google GSON library, adds the Google Maven repository to all modules, and updates all compile/testCompile references to their non-deprecated versions.

## What was wrong?

The versions were simply out of date and needed updating and verification that no problems occurred as a result.

## How's it fixed?

1. All the versions were updated at first, however, they needed the Google repository.

2. I added the Google Maven repository in the build files so they could be located.

3. The build files still used `compile` and `testCompile` which was throwing warnings about the plan to [stop supporting them][1] by the end of 2018 so I updated their references:
    - In the app `build.gradle` file, they needed to be changed to `implementation` and `testImplementation` respectively.
    - In the library's `build.gradle` file, they needed to be changed to `api` and `testImplementation` respectively.

[1]: https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration#new_configurations

### CODE REVIEW

**Comment by 4lch4** [comment]
Awww, looks like the Travis build has failed. Looking into that now..

**Comment by 4lch4** [comment]
Hmm... Not too sure what the issue is with the latest build.. I'll see what I can figure out.

**Comment by 4lch4** [comment]
I'm honestly at a loss for what to do to fix [the Travis build][1]. Anyone have a suggestion?

Build log:

```
* What went wrong:
Could not determine the dependencies of task ':app:testDebugUnitTest'.
> Task with path 'unzipJacocoAgent' not found in project ':app'.
```

[1]: https://travis-ci.org/coding-blocks/DigitalOceanApp/jobs/380543167

**Comment by championswimmer** [comment]
@Alcha 
You'll have to follow this to setup unified coverage https://proandroiddev.com/unified-code-coverage-for-android-revisited-44789c9b722f 

You need to remove `jacoco-everywhere` plugin. It is deprecated

**Comment by 4lch4** [comment]
Thanks, @championswimmer, I'll be sure to get that fixed and submit a new commit soon.

**Comment by 4lch4** [comment]
Alrighty, I have some time now so I'm gonna get this fixed.

**Comment by 4lch4** [comment]
_schweeeeeeet, it's fixed!

Dancing

@championswimmer if you'd like to merge the PR it shouldn't cause any more problems as I updated to the new Jacoco plugin per the guide you linked. Thank you for that.

**Pull request merged**
