### PR TITLE
Fixed Travis Error

### LINKED ISSUE #104: fix travis build (after release keys were added)
don't execute this line

https://github.com/coding-blocks/DigitalOceanApp/blob/master/app/build.gradle#L142-L143

if on travis

### PR DESCRIPTION
**Pull request by aggarwalpulkit596**
Fix #104

### CODE REVIEW

**Comment by aggarwalpulkit596** [comment]
@championswimmer thank you bhaiya for this i was having error myself while uploading raw map styling files 👍 
image

**Comment by aggarwalpulkit596** [comment]
@championswimmer travis was errored due to timeout rest all is good i guess 👍

**Comment by aggarwalpulkit596** [comment]
Again Timed out @championswimmer 
image

**Comment by championswimmer** [comment]
I think the fix is not correct. It shouldn't try to read the keys directory, not just ignore it's existence. I'll check

**Comment by aggarwalpulkit596** [comment]
We can use deploy our keys to travis there is method for that also

**Comment by aggarwalpulkit596** [comment]
https://android.jlelse.eu/using-travisci-to-securely-build-and-deploy-a-signed-version-of-your-android-app-94afdf5cf5b4

**Comment by championswimmer** [comment]
this works 

https://github.com/coding-blocks/Chatter/commit/d0ea350d85c0f9fe803f83806c0722220e258b51

try this here

**Pull request merged**
